name: Build and Push Go Code to Github Container Registry

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/wordpress-exporter:${{ github.ref_name }} -t ghcr.io/${{ github.repository }}/wordpress-exporter:latest .

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository }}/wordpress-exporter:${{ github.ref_name }} ghcr.io/${{ github.repository }}/wordpress-exporter:latest

      - name: Cleanup
        run: |
          docker image rm ghcr.io/${{ github.repository }}/wordpress-exporter --all-tags
          docker logout ghcr.io
